version: '2'
services:
  redis-cluster:
    environment:
     IP: 0.0.0.0
     SENTINEL: ${REDIS_USE_SENTINEL}
     STANDALONE: ${REDIS_USE_STANDALONE}
     CLUSTER_ONLY: 'true'
    build:
      context: .
      args:
        redis_version: '5.0.4'
    hostname: server
    ports:
      - '7000-7007:7000-7007'
      - '5000-5002:5000-5002'
